-- Tasks table
-- Created from MIA session output — enterprise never writes a raw brief

create type task_status as enum (
  'pending_review',    -- submitted, awaiting Gate 1
  'revision_needed',   -- Gate 1 flagged, enterprise must address
  'approved',          -- Gate 1 passed, open for contributors
  'in_progress',       -- contributors actively working
  'completed',         -- all submissions received
  'processed',         -- MCGA cross-check done, deliverable ready
  'delivered',         -- enterprise has received deliverable
  'canceled'
);

create type task_type as enum (
  'text_rating',
  'voice_collection',
  'annotation',
  'comparative_evaluation',
  'open_ended_response'
);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  enterprise_id uuid references public.enterprise_profiles(id) on delete cascade not null,
  mia_session_id uuid references public.mia_sessions(id) on delete set null,

  -- Task definition — generated by MIA, reviewed by Gate 1
  task_type task_type not null,
  title text not null,
  description text not null,
  instructions text not null,
  compensation_per_task numeric(10,2) not null,  -- what contributor earns per submission
  volume integer not null,                        -- number of submissions requested
  demographic_requirements jsonb,                 -- targeting criteria from CAGA routing

  -- MIA context — critical: never remove, MCGA depends on this for quality cross-check
  mia_context jsonb,                              -- full CCF + goals + gaps from MIA session

  -- Progress tracking
  task_status task_status not null default 'pending_review',
  submissions_received integer not null default 0,
  submissions_approved integer not null default 0,

  -- Tier at time of task creation — for billing and feature gate enforcement
  tier_at_creation subscription_tier not null,

  -- Timestamps
  approved_at timestamptz,
  completed_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add FK back to mia_sessions now that tasks exists
alter table public.mia_sessions
  add constraint mia_sessions_resulting_task_id_fkey
  foreign key (resulting_task_id) references public.tasks(id) on delete set null;

create trigger tasks_updated_at
  before update on public.tasks
  for each row execute function public.handle_updated_at();

create index tasks_enterprise_id_idx on public.tasks(enterprise_id);
create index tasks_status_idx on public.tasks(task_status);
create index tasks_mia_session_id_idx on public.tasks(mia_session_id);
